### ISSUE TITLE
Feature request: pass a command to `render ssh` as a flag

### ISSUE THREAD

**Issue by brettchalupa** [render-oss/cli#10]
I'd love it if I could pass a flag to `render ssh` that runs the command as soon as it connects. It's really common to boot up an interactive REPL like the Ruby on Rails console.

So, for example:

```console
render ssh srv-abc123 --command "bundle exec rails console"
render ssh -c srv-abc123 "bundle exec rails console"
```

**Comment by mdbenjam** [comment]
In this [commit](https://github.com/render-oss/cli/commit/2ac8ed6b1dc3080b7b5c998edf4306a89e9f8d97) in release 1.1.0 we allow you to pass args on to ssh, psql, pgcli, and redis-cli. You'll just need to do `--` before any args you want to be passed on. For example:

```
render ssh <service-id> -- echo 'hello world'
```

Going to close this, but feel free to reopen the issue if this doesn't address your needs.

**Comment by brettchalupa** [comment]
@mdbenjam thank you for adding this!

I can confirm I'm able to boot an interactive console with `render ssh srv-abc123 -- "cd /rails; bin/rails c"`

But I'm not seeing the normal output from the command that I'd expect:

## Expected

This is how it looks when I do `render ssh src-abc123` and then when the shell starts, I run: `cd /rails; bin/rails c`:

<img width="997" alt="image" src="https://github.com/user-attachments/assets/87f19f66-0939-490d-b147-c1ba12933ca9">


## Actual
<img width="864" alt="image" src="https://github.com/user-attachments/assets/61707371-2f6b-4d58-892a-52288fd1806b">

So it seems like there's something off with the way the connection is working or something. I'll keep experimenting but figured I'd share an early report on how it's behaving.

**Comment by mdbenjam** [comment]
Could you try passing in `-t`. When you pass a command to ssh it doesn't allocate a pseudo-terminal. -t forces this and I think should get back your formatting.

**Comment by brettchalupa** [comment]
Thank yo so much, that does it! Running `render ssh srv-abc123 -- -t "cd /rails; bin/rails c"` accomplishes exactly what I was hoping for. 🎉
