### ISSUE TITLE
Instructions to install latest release on Linux

### ISSUE THREAD

**Issue by piotr-cz** [render-oss/cli#12]
At this moment, the recommended installation is only for MacOS with Homebrew.
Alternative installation from source requires GO.
Installing homebrew on a linux just to install this package is overkill

It would help if installation instructions similar to Homebrew would be available for Linux (Alpine Linux), to use CLI in GitLab pipelines/ Github Actions.

Or if there would be an installation script, such as one of:

- dotenvx: https://dotenvx.sh
- nvm: https://github.com/nvm-sh/nvm

**Comment by piotr-cz** [comment]
This works on Alpine Linux:

```shell
echo "Installing Render CLI"
wget https://github.com/render-oss/cli/releases/download/v0.8.6/cli_0.8.6_linux_amd64.zip
unzip cli_0.8.6_linux_amd64.zip -d render-cli
chmod +x render-cli/cli_v0.8.6
alias render="render-cli/cli_v0.8.6"
```

**Comment by jakemalachowski** [comment]
We added an install script to get the latest version. Could you try running this? 

`curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh`

**Comment by piotr-cz** [comment]
I can confirm, that above install script works in `node:18.18.2-alpine` docker image
