### ISSUE TITLE
bug: Log search/filter does not work

### ISSUE THREAD

**Issue by iwilltry42** [render-oss/cli#6]
Hey there! You built a really nice TUI :)

I'm hitting a bug in the log view though.
When I pull up the filter menu via `/` and hit Enter (with or without actually using any filter), I hit the following error: `failed to parse form values: unsupported type: struct`

CLI: `render version 0.8.3`

**Comment by iwilltry42** [comment]
Cool, thanks for the quick [fix](https://github.com/render-oss/cli/commit/acd129ac029fa894d96e32b06890c6714c6348c3) :)

**Comment by jakemalachowski** [comment]
Thanks for the report! This is fix will be included in`v0.8.4`
