### ISSUE TITLE
`render deploys list` does not show the interactive service selector

### ISSUE THREAD

**Issue by brettchalupa** [render-oss/cli#8]
The new Render CLI has been great so far! It's snappy and working well. I noticed that when I run `render ssh` there's a nice interactive TUI for selecting my service.

It'd be great if `render deploys list` showed the same interactive selector for the service rather than having to paste in the ID.

Screenshot of the UI I'm referring to:

<img width="679" alt="Screenshot 2024-11-25 at 3 28 11 PM" src="https://github.com/user-attachments/assets/adb626b1-89a5-44ff-b1b7-8bc5fb01c91a">

**Comment by kitemongerer** [comment]
Thanks for the feedback @brettchalupa! We've added this and it will be available in the next release

**Comment by brettchalupa** [comment]
@kitemongerer thank you! 🙌
